PyTorch basics & Autograd



## CPU, GPU

In [ ]:
# Get OS info
!cat /etc/issue.net

Ubuntu 20.04.5 LTS


In [5]:
# Get CPU info
!cat /proc/cpuinfo | grep 'processor\|model name\|cpu cores'

processor	: 0
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
cpu cores	: 1
processor	: 1
model name	: Intel(R) Xeon(R) CPU @ 2.30GHz
cpu cores	: 1


In [4]:
# Get GPU info
!nvidia-smi

Wed Mar 15 16:06:28 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P0    27W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

## Pytorch, Tensor

In [8]:
import torch

In [ ]:
torch.__version__

'1.13.1+cu116'

In [ ]:
!pip show torch

Name: torch
Version: 1.13.1+cu116
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.9/dist-packages
Requires: typing-extensions
Required-by: fastai, torchaudio, torchtext, torchvision


## 1.1 Tensor Basic

In [9]:
#Tensor의 기초적 선언
#torch.FloatTensor와 같음
# x = torch.Tensor(행, 열)
x = torch.Tensor(2, 3)
print(x)

tensor([[ 2.0355e-20,  4.5787e-41,  1.9953e-20],
        [ 4.5787e-41,  1.0715e-02, -4.8486e-08]])


In [10]:
#Tesnor의 정보 확인
print("Tensor Type : ", type(x))
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size()) # x.shape

Tensor Type :  <class 'torch.Tensor'>
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


## 1.2 Tensor with characteristics

In [11]:
#0으로 채워진 Tensor 선언
x = torch.zeros(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [12]:
x = torch.zeros(2,3, dtype=torch.int32)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#1로 채워진 Tensor 선언
x = torch.ones(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#0, 1 사이의 랜덤 숫자로 채워진 Tensor 선언
x = torch.rand(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[0.6250, 0.5824, 0.3714],
        [0.5825, 0.2517, 0.3137]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#평균이 0이고 분산이 1을 따르는 정규분포에서 추출된 값으로 채워진 Tensor 선언
x = torch.randn(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[ 1.4835,  0.0624, -1.7620],
        [-0.5942,  1.3545, -1.7614]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#정방행렬과 같은 Tensor 선언
x = torch.eye(2, 3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 0., 0.],
        [0., 1., 0.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#0부터 2까지 0.5씩 증가하는 Tensor 선언
x = torch.arange(0, 2, step=0.5)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([0.0000, 0.5000, 1.0000, 1.5000])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([4])


In [ ]:
#직접 값을 입력하여 선언
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#32-bit floating point
x = torch.FloatTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[4.7131e-16, 3.0740e-41, 3.3631e-44],
        [0.0000e+00,        nan, 3.0000e+00]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
#32-bit integer (signed)
x = torch.IntTensor(2,3)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[638048512,     21937, 528784896],
        [    21937,        24,         0]], dtype=torch.int32)
Tensor Type :  torch.IntTensor
Tensor Size :  torch.Size([2, 3])


## 1.3 Tensor and Numpy

In [15]:
import numpy as np

In [16]:
#numpy 형식의 배열
x = np.array([[1,2,3],[1,2,3]])
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


In [17]:
#numpy를 tensor로 변환
x = torch.from_numpy(x) # x = torch.Tensor(x)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1, 2, 3],
        [1, 2, 3]])
Tensor Type :  torch.LongTensor
Tensor Size :  torch.Size([2, 3])


In [18]:
#tensor를 numpy로 변환
x = x.numpy()
print(x, type(x))

[[1 2 3]
 [1 2 3]] <class 'numpy.ndarray'>


## 1.4 Tensor Slicing

In [19]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [20]:
#모든 원소 출력
x[:, :]

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
#2행부터 출력
x[1:, :]

tensor([[ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
#2열부터 출력
x[:, 1:]

tensor([[ 2.,  3.,  4.],
        [ 6.,  7.,  8.],
        [10., 11., 12.]])

In [ ]:
#2행, 2열부터 3열까지 출력
x[1:, 1:3]

tensor([[ 6.,  7.],
        [10., 11.]])

In [ ]:
#1행 출력
x[0, :]

tensor([1., 2., 3., 4.])

In [ ]:
#x를 1행씩 잘라서 배열로 저장
x_rows = torch.split(x, split_size_or_sections=1, dim=0)
print(x_rows)

(tensor([[1., 2., 3., 4.]]), tensor([[5., 6., 7., 8.]]), tensor([[ 9., 10., 11., 12.]]))


In [ ]:
#x를 2열씩 잘라서 배열로 저장
x_cols = torch.split(x, split_size_or_sections=2, dim=1)
print(x_cols)

(tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]]), tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]]))


In [ ]:
#위와 같은 결과
torch.chunk(x, chunks=2, dim=1)

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]), tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

## 1.5 Tensor Merging

In [ ]:
#x_rows를 행으로 이어 붙이기
torch.cat(x_rows, dim=0)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [ ]:
#x_rows를 열로 이어 붙이기
torch.cat(x_rows, dim=1)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [ ]:
#x_cols를 쌓아올리기
x_new = torch.stack(x_cols, dim=0)
print(x_new)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])


## 1.6 Tensor Reshaping

In [54]:
x = torch.Tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [55]:
#4행 3열로 바꾸기
x.view(4, 3)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

In [56]:
#2열로 바꾸기
x.view(-1, 2)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [57]:
x.view(2, 1, -1)

tensor([[[ 1.,  2.,  3.,  4.,  5.,  6.]],

        [[ 7.,  8.,  9., 10., 11., 12.]]])

In [60]:
#차원이 1인 값을 축소: (2,6)
x.view(2, 1, -1).squeeze()

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [63]:
#dim=1 자리에 차원을 추가: (2,1,6)
x.view(2, 1, -1).squeeze().unsqueeze(dim=1).size()

torch.Size([2, 6, 1])

## 1.7 Tensor Calculation

In [ ]:
x = torch.Tensor([[1,2,3],[4,5,6]])
y = torch.Tensor([[1,1,1],[2,2,2]])
print("x :", x)
print("y :", y)

x : tensor([[1., 2., 3.],
        [4., 5., 6.]])
y : tensor([[1., 1., 1.],
        [2., 2., 2.]])


In [ ]:
# x와 y의 합
z = torch.add(x, y)
print("z :", z)
print("x+y :", x+y)

z : tensor([[2., 3., 4.],
        [6., 7., 8.]])
x+y : tensor([[2., 3., 4.],
        [6., 7., 8.]])


In [ ]:
# x의 모든 원소에서 2를 뺌
print(x - 2)

# x의 모든 원소에 2를 곱함
print(2*x)

tensor([[-1.,  0.,  1.],
        [ 2.,  3.,  4.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [ ]:
#x의 원소와 y의 원소를 각각 곱함
z = torch.mul(x, y)
print("z :", z)
print("x*y :", x*y)

z : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])
x*y : tensor([[ 1.,  2.,  3.],
        [ 8., 10., 12.]])


In [ ]:
#x의 원소를 각각 제곱함
z = torch.pow(x, 2)
print("z :", z)
print("x**2 :", x**2)

z : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])
x**2 : tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])


In [ ]:
#x의 원소에 log를 씌움
z = torch.log(x)
print("z :", z)
print("x.log() :", x.log())

z : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])
x.log() : tensor([[0.0000, 0.6931, 1.0986],
        [1.3863, 1.6094, 1.7918]])


In [ ]:
#x의 원소에 루트를 씌움
z = torch.sqrt(x)
print("z :", z)
print("x.sqrt() :", x.sqrt())

z : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
x.sqrt() : tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])


In [ ]:
#x의 원소에 나머지(mod) 계산
z = x % 2
print(z)

tensor([[1., 0., 1.],
        [0., 1., 0.]])


In [ ]:
#x에 절댓값
z = torch.abs(x)
print("z :", z)
print("x.abs() :", x.abs())

z : tensor([[1., 2., 3.],
        [4., 5., 6.]])
x.abs() : tensor([[1., 2., 3.],
        [4., 5., 6.]])


## 1.9 Tensor Statistic

In [ ]:
x = torch.Tensor([[-1,2,-3],[4,-5,6]])
print(x)

tensor([[-1.,  2., -3.],
        [ 4., -5.,  6.]])


In [ ]:
print("x의 합 :", x.sum())
print("x의 최대값 :", x.max())
print("x의 최소값 :", x.min())
print("x의 분산 :", x.var())

x의 합 : tensor(3.)
x의 최대값 : tensor(6.)
x의 최소값 : tensor(-5.)
x의 분산 : tensor(17.9000)


In [ ]:
# Scalar Tensor
x.sum().size()

torch.Size([])

In [ ]:
# item의 활용
print("x의 합 :", x.sum().item())
print("x의 최대값 :", x.max().item())
print("x의 최소값 :", x.min().item())
print("x의 분산 :", x.var().item())

x의 합 : 3.0
x의 최대값 : 6.0
x의 최소값 : -5.0
x의 분산 : 17.899999618530273


In [ ]:
#행(dim=0)을 기준으로 열의 최댓값을 출력
value, index = x.max(dim=0)
value, index

(tensor([4., 2., 6.]), tensor([1, 0, 1]))

In [ ]:
#열(dim=1)을 기준으로 행의 최댓값을 출력
value, index = x.max(dim=1)
value, index

# torch.max(x, dim=1)과 같은 결과
# 이는 추후에 계속 등장하므로 매우 중요!

(tensor([2., 6.]), tensor([1, 2]))

In [ ]:
#열(dim=1)을 기준으로 각 행을 정렬
value, index = x.sort(dim=1)
value

tensor([[-3., -1.,  2.],
        [-5.,  4.,  6.]])

## 1.11 Tensor for GPU

In [44]:
# cuda 확인
print("현재 Cuda 사용 가능한 Device 개수 :", torch.cuda.device_count())
print("현재 Cuda 사용 가능 여부 :", torch.cuda.is_available())
print("현재 사용 중인 Cuda Device :", torch.cuda.current_device())
print("현재 Cuda Device 이름 :", torch.cuda.get_device_name(0))
print("현재 Cuda Device의 사용 가능한 메모리 :", torch.cuda.max_memory_allocated(device=0), "bytes")
print("현재 Cuda Device의 사용 중인 메모리 :", torch.cuda.memory_allocated(device=0), "bytes")

현재 Cuda 사용 가능한 Device 개수 : 1
현재 Cuda 사용 가능 여부 : True
현재 사용 중인 Cuda Device : 0
현재 Cuda Device 이름 : Tesla T4
현재 Cuda Device의 사용 가능한 메모리 : 0 bytes
현재 Cuda Device의 사용 중인 메모리 : 0 bytes


In [45]:
# cuda 세팅
torch.cuda.set_device(0)

In [46]:
x = torch.Tensor([[1,2,3],[1,2,3]])
print(x)

tensor([[1., 2., 3.],
        [1., 2., 3.]])


In [47]:
#cpu를 gpu로 전환
gpu_x = x.cuda()
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [48]:
#cpu를 gpu로 전환 2
device = torch.device("cuda")
gpu_x = x.to(device)
print(gpu_x)
print("Tensor Type : ", gpu_x.type())
print("Tensor Size : ", gpu_x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0')
Tensor Type :  torch.cuda.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [49]:
#gpu를 cpu로 전환
x = gpu_x.cpu()
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [50]:
#gpu를 cpu로 전환 2
device = torch.device("cpu")
x = gpu_x.to(device)
print(x)
print("Tensor Type : ", x.type())
print("Tensor Size : ", x.size())

tensor([[1., 2., 3.],
        [1., 2., 3.]])
Tensor Type :  torch.FloatTensor
Tensor Size :  torch.Size([2, 3])


In [ ]:
# gpu tensor와 cpu tensor의 연산
gpu_x + x

RuntimeError: ignored

## 1.12 Tensor Calculation as Matrix (참고)

In [ ]:
x = torch.Tensor([[1,1],[2,2]])
y = torch.Tensor([[1,2],[3,4]])
print("x :", x)
print("y :", y)

x : tensor([[1., 1.],
        [2., 2.]])
y : tensor([[1., 2.],
        [3., 4.]])


In [ ]:
#x와 y의 행렬곱
torch.mm(x, y)

tensor([[ 4.,  6.],
        [ 8., 12.]])

In [ ]:
#x와 z의 행렬벡터곱
z = torch.Tensor([1, 2])
torch.mv(x, z)

tensor([3., 6.])

In [ ]:
#z와 z의 내적
torch.dot(z, z)

tensor(5.)

In [ ]:
#x의 전치(transpose)
x.t()

tensor([[1., 2.],
        [1., 2.]])

In [ ]:
# y의 역행렬(inverse)
y.inverse()

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

In [ ]:
# 텐서의 배치 행렬곱
x1 = torch.FloatTensor(3,3,2)
x2 = torch.FloatTensor(3,2,3)

torch.bmm(x1,x2).size()

torch.Size([3, 3, 3])

In [ ]:
x1

tensor([[[4.1584e+35, 3.0740e-41],
         [7.0065e-44, 7.0065e-44],
         [6.3058e-44, 6.7262e-44]],

        [[7.2868e-44, 6.3058e-44],
         [6.7262e-44, 7.5670e-44],
         [1.1771e-43, 6.7262e-44]],

        [[7.5670e-44, 8.1275e-44],
         [7.1466e-44, 7.9874e-44],
         [8.1275e-44, 7.4269e-44]]])

In [ ]:
# 텐서의 전치
x1.transpose(0,2)

tensor([[[4.1584e+35, 7.2868e-44, 7.5670e-44],
         [7.0065e-44, 6.7262e-44, 7.1466e-44],
         [6.3058e-44, 1.1771e-43, 8.1275e-44]],

        [[3.0740e-41, 6.3058e-44, 8.1275e-44],
         [7.0065e-44, 7.5670e-44, 7.9874e-44],
         [6.7262e-44, 6.7262e-44, 7.4269e-44]]])

In [ ]:
eigenvalue, eigenvector = torch.eig(x,eigenvectors=True)
print("eigenvalue :", eigenvalue)
print("eigenvector :", eigenvector)

eigenvalue : tensor([[1.1921e-07, 0.0000e+00],
        [3.0000e+00, 0.0000e+00]])
eigenvector : tensor([[-0.7071, -0.4472],
        [ 0.7071, -0.8944]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2894.)
  """Entry point for launching an IPython kernel.


In [ ]:
#행렬의 QR factorization
Q,R = torch.qr(x)
print("Q :", Q)
print("R :", R)

Q : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
R : tensor([[-2.2361e+00, -2.2361e+00],
        [ 0.0000e+00,  1.1921e-07]])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:1937.)
  


In [ ]:
#행렬의 SVD factorization
S,V,D = torch.svd(x)
print("S :", S)
print("V :", V)
print("D :", D)

S : tensor([[-0.4472, -0.8944],
        [-0.8944,  0.4472]])
V : tensor([3.1623e+00, 5.2283e-08])
D : tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]])


# 2. Autograd

In [ ]:
import torch

## 2.1 Autograd 

In [21]:
x = torch.ones(1)
x.requires_grad

False

In [22]:
y = torch.ones(1)
y.requires_grad

False

In [23]:
z = x + y

In [24]:
z.requires_grad

False

In [25]:
x.requires_grad=True
x.requires_grad

True

In [26]:
z = x + y

In [27]:
z.requires_grad

True

## 2.2 Backward

In [36]:
y = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32, requires_grad=True)
y

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [37]:
z = 2*y + 1
z

tensor([[3., 5.],
        [7., 9.]], grad_fn=<AddBackward0>)

In [38]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)

y.requires_grad : True
z.requires_grad : True

y.grad : None
z.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x7fa31e6f6520>


<ipython-input-38-e8263d7c80e3>:7: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  print("z.grad :", z.grad)


In [ ]:
# grad can be implicitly created only for scalar outputs
z.backward()

RuntimeError: ignored

In [39]:
out = z.sum()
out

tensor(24., grad_fn=<SumBackward0>)

In [40]:
print("y.requires_grad :", y.requires_grad)
print("z.requires_grad :", z.requires_grad)
print("out.requires_grad :", out.requires_grad)

print("")

print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.requires_grad : True
z.requires_grad : True
out.requires_grad : True

y.grad : None
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x7fa31e7075e0>
out.grad_fn : <SumBackward0 object at 0x7fa31e707970>


<ipython-input-40-87717518aad1>:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  print("z.grad :", z.grad)
<ipython-input-40-87717518aad1>:9: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 

In [41]:
out.backward()

In [42]:
print("y.grad :", y.grad)
print("z.grad :", z.grad)
print("out.grad :", out.grad)

print("")

print("y.grad_fn :", y.grad_fn)
print("z.grad_fn :", z.grad_fn)
print("out.grad_fn :", out.grad_fn)

y.grad : tensor([[2., 2.],
        [2., 2.]])
z.grad : None
out.grad : None

y.grad_fn : None
z.grad_fn : <AddBackward0 object at 0x7fa31e6f6ca0>
out.grad_fn : <SumBackward0 object at 0x7fa31e6f6940>


<ipython-input-42-92d971a14ffb>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:480.)
  print("z.grad :", z.grad)
<ipython-input-42-92d971a14ffb>:3: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 

## 2.3 Detach from Autograd & .detach() vs .data

In [ ]:
# Graph 위에 있는 변수는 바로 numpy로 변환할 수 없음.
z.numpy()

RuntimeError: ignored

In [ ]:
# 따라서 .detach와 .data 중 하나를 사용해야함.
z.detach().numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)

In [ ]:
# 따라서 .detach와 .data 중 하나를 사용해야함.
z.data.numpy()

array([[3., 5.],
       [7., 9.]], dtype=float32)